### ISSUE TITLE
Design an icon for the project

### ISSUE THREAD

**Issue by PohSayKeong** [fossasia/flappy-svg#10]
Create a 128x128 icon and place in the icons directory, make sure it's in .svg format.

**Comment by niccokunzmann** [comment]
Should it be in .ico format, too? It could also be the icon of the index.html file. there are meta tags to set the icon.

**Comment by PohSayKeong** [comment]
Yeah preferably both.

**Comment by anniezhou301** [comment]
How's this for an icon? It has two humps to show the camel, and has a landscape-esque feel to it, whose colors match the background of the game. I have it in svg and ico format as well, and can make changes. 
![favicon](https://cloud.githubusercontent.com/assets/8906927/12038780/d9bb091c-ae28-11e5-975e-1d51b0567d76.png)
.

**Comment by jig08** [comment]
In my humble opinion, it could be better :)

**Comment by niccokunzmann** [comment]
Can you remove the black lines or make them very important? You should look at it when it is about 20x20 pixels which is the size it has in the browser window. Small things like the lines will not be recognized. I like the humps as they are the movement that the different figures make. (click on the camel and you get a bat)

 @PohSayKeong What do you think?

**Comment by sudheesh001** [comment]
@anniezhou301 , That's a great icon, in my suggestion, drop the solid black lines and add a shadow like those of flat icons.
![featured13 wdd2x](https://cloud.githubusercontent.com/assets/4545925/12042727/bfffe48c-ae8e-11e5-966e-f4f15f5ed973.jpg)

**Comment by anniezhou301** [comment]
Yup, I'll rework it. Thanks!

**Comment by anniezhou301** [comment]
How's this design?
![favicon](https://cloud.githubusercontent.com/assets/8906927/12043810/bda89acc-ae56-11e5-8bbe-f3c1e5326e03.png)

**Comment by PohSayKeong** [comment]
I feel that it's pretty nice and relevant as well considering the fact that the all the characters are included in the logo. It should work fine for a start, but in the future when there are more and more characters, an update will probably be needed.

**Comment by jig08** [comment]
@sudheesh001 , @niccokunzmann +1 on removing the solid lines and adding a shadow.
@anniezhou301 Yes, This looks nice. As @PohSayKeong says, it encompasses the characters relevantly.

**Comment by sudheesh001** [comment]
@anniezhou301 That's really good work.

**Comment by anniezhou301** [comment]
Thank you! Any suggestions?

**Comment by jig08** [comment]
Make a PR ? :wink:

**Comment by niccokunzmann** [comment]
@anniezhou301 Cool! Are you familiar enough with Github to make a pull-request? You can search how to do this. The process should be roughly:
1. fork this repository
2. add your files (You should also add your name to the Contributors.md file)
3. create a pull-request

**Comment by niccokunzmann** [comment]
Ok, I found it. Usually you would reference this issue in the pull request with "#10". Here are some other remarks:
Can you
- add your name to the contributors.md file?
- make the icon used by the index.html file? stackoverflow.com/questions/9943771/adding-a-favicon-to-a-static-html-page
Both is possible as one pull-request.

**Comment by niccokunzmann** [comment]
Thanks a lot for this beautiful icon! If you want to go on with this game, you can choose from the other tasks. If you have questions, you can ask. Adding a new character or a new background could be a next step.

**Comment by anniezhou301** [comment]
Definitely! I just want to thank everyone for being so helpful and supportive. It was a lot of fun working with you guys.
