### ISSUE TITLE
Responsive Main Menu

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#107]
**Problem**
Currently, the Main Menu has some fixed positions for elements. The buttons are not visible if the width of the page is thin. 

**Solution**
Move the buttons with the size of the page so that they stay visible. e.g. center them. 

**Hints**
In #104 you see who created the menu and you can ask for help here.

Comment if you would like to work on this issue.

**Comment by kamishettysreeja25** [comment]
@niccokunzmann 
Should the size of the buttons also change with the size of the window ?

**Comment by niccokunzmann** [comment]
@kamishettysreeja25 There can be solutions that resize the buttons and there can be solutions which do not resize the buttons. I do not decide that.

**Comment by kamishettysreeja25** [comment]
@niccokunzmann 
I have worked on this and resized both the size of the button and moved the buttons with the size of the window
the output looks something like this when  we decrease the size of the window is this fine ? 
![screenshot from 2016-02-25 23 14 45](https://cloud.githubusercontent.com/assets/14835922/13328645/c5d656ac-dc15-11e5-88c2-b3a92da63912.png)

**Comment by niccokunzmann** [comment]
@kamishettysreeja25 Do you have source code? I would test re-sizing the window. I do not know how it responds from the picture.

**Comment by harry-7** [comment]
@niccokunzmann Check the pull request and comment on status. I changed appearance a bit. Is that fine ?

**Comment by niccokunzmann** [comment]
@harry-7 this is what I had in mind.
