### ISSUE TITLE
Add Instructions to play the game 

### ISSUE THREAD

**Issue by kamishettysreeja25** [fossasia/flappy-svg#109]
Currently we have developed the main menu . 
We need to add the controls for the game , the scoring schema etc 
Design the howtoplay.html file in a user friendly way.

**Comment by kamishettysreeja25** [comment]
@niccokunzmann  
I have created the basic layout of the game instructions if there should be any changes please suggest me :) 
![screenshot from 2016-02-26 17 53 15](https://cloud.githubusercontent.com/assets/14835922/13352241/f631a8f0-dcb1-11e5-8aff-729c83d4dfb3.png)

**Comment by niccokunzmann** [comment]
@kamishettysreeja25 Can you show some code? would like to test it out. You can do a pull-request and we talk there :)
