### ISSUE TITLE
Score updation required

### ISSUE THREAD

**Issue by daminisatya** [fossasia/flappy-svg#112]
Instead of placing a static score label, tentatively the score can be calculated based on the number of obstacles being crossed . The complexity of the score can be increased based on various parameters like speed, distance etc.

**Comment by niccokunzmann** [comment]
Good idea! If someone wants to do that, welcome.

**Comment by harry-7** [comment]
I want to work on this. I would be glad if someone can guide me as to where and how to start :)

**Comment by niccokunzmann** [comment]
@harry-7 My thoughts: the [Flappy](https://github.com/fossasia/flappy-svg/blob/gh-pages/javascript/flapping.js#L11) updates the score whenever something happens.

Also, there is the score label at the top. Somehow, you can change the content of it. The functionality of the score does not belong in the Flappy class. Maybe it has its own file.

My answer is pretty vague. If you have more questions, you can ask.

**Comment by harry-7** [comment]
@niccokunzmann Yeah I saw the score label and how to change it. My doubt was how do I keep track of obstacles crossed?

**Comment by niccokunzmann** [comment]
There is collision detection implemented.
https://github.com/fossasia/flappy-svg/blob/gh-pages/javascript/flapping.js#L50
It knows, when an obstacle is hit. Thus, it should be possible to modify
it so you know, when an obstacle is passed.
Do you know what this does
https://github.com/fossasia/flappy-svg/blob/gh-pages/javascript/flapping.js#L60
?
------------------------------------------------------------------------

I think this issue can be split into two parts:

- [ ] change the score label
- [ ] find out when behind obstacle

Am 26.07.2016 um 14:49 schrieb Hemanth Kumar Veeranki:

**Comment by harry-7** [comment]
https://github.com/fossasia/flappy-svg/blob/gh-pages/javascript/flapping.js#L60
I think instead of creating new obstacles you are just shifting them forward.Am I  right ? 
Ok I ll look into the collision part once

**Comment by niccokunzmann** [comment]
@daminisatya @harry-7 would you close this issue? Else, what else would you wish to see implemented?

**Comment by harry-7** [comment]
I guess we can close the issue as the score update is being done. @daminisatya  are there any more specifications ?

**Comment by niccokunzmann** [comment]
Okay, closing it!
