### ISSUE TITLE
Choose Space Background by Click

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#131]
The space background by @Antrismus  is chosen only randomly. Add a button like for the other backgrounds, to choose this one.

**Comment by Baidya99** [comment]
I would like to do this.

**Comment by niccokunzmann** [comment]
Sure, please go ahaed.

**Comment by niccokunzmann** [comment]
@Baidya99 Thanks for your commit!

**Comment by niccokunzmann** [comment]
I checked all the pictues and two of them did not change the background. Is this intended? I do not know how many backgrounds are there...

**Comment by Abhi2424shek** [comment]
@niccokunzmann they all are working...
