### ISSUE TITLE
Windows App: Create Download

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#135]
Problem: I want to play Flappy-SVG on Windows (#132) and I  do not know, what to download.

Possible Sulution:
- [X] Either create a flappy-SVG-installer or a zip-file to download that runs on Windows.
- [x] Create a link to this downloadable thing in the README.md file in the master branch.

**Comment by adarsh-ideal** [comment]
@niccokunzmann I think you already added the link in README.md. I can see that.
Thanks!
