### ISSUE TITLE
Add download link for Windows App to links.html

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#137]
The [links.html](http://fossasia.github.io/flappy-svg/links.html) file is used as a starting point, to get the game. The Windows app should be there with a nice self-made Windows icon.

**Comment by adarsh-ideal** [comment]
@niccokunzmann I am doing that and will inform you after adding the link.

**Comment by niccokunzmann** [comment]
Sure!

**Comment by adarsh-ideal** [comment]
Added Download link.
PR: https://github.com/fossasia/flappy-svg/pull/145
gh-pages: https://adarsh-ideal.github.io/flappy-svg/

**Comment by niccokunzmann** [comment]
Thanks!
