### ISSUE TITLE
Some of the character dont have onclick attributes.

### ISSUE THREAD

**Issue by Baidya99** [fossasia/flappy-svg#156]

**Comment by niccokunzmann** [comment]
The title is an observation. If you like, you can also add something in the form:
[Observation] This leads to [Problem]. If you wan to solve it you can [Hints]

**Comment by Baidya99** [comment]
Can I resolve this myself?

**Comment by niccokunzmann** [comment]
Yes.

**Comment by niccokunzmann** [comment]
#158 is a follow-up issue which should be easy for you. If you like, you can do it.
