### ISSUE TITLE
Hide Space-Ship on click

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#158]
I just played the game, clicked through all the characters and the space ship did not disappear.

Solution: When I click the space ship, it should disappear and only one character should be seen.

**Comment by Baidya99** [comment]
Okay I want to do this.

**Comment by niccokunzmann** [comment]
Please, go ahead, have fun :)

**Comment by niccokunzmann** [comment]
@Baidya99 Is there any task which I should accept?

**Comment by Baidya99** [comment]
None.
