### ISSUE TITLE
Connect new characters via click

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#172]
I saw new characters like two unicorns and a robot #171.
Which new characters are there? They should be reachable somehow via click.

**Comment by hemanthsavasere** [comment]
I will work on this @niccokunzmann

**Comment by niccokunzmann** [comment]
Sure. Have fun :)

**Comment by Marauderer97** [comment]
Hey, is this fixed? If not I would like to try fixing it :)

**Comment by hemanthsavasere** [comment]
This is fixed.
