### ISSUE TITLE
Source of opensource.jpg 

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#176]
@hemanthsavasere What is the source of opensource.jpg ? Which license is it under?
If we are allowed to use it, please create a license file for it.

**Comment by hemanthsavasere** [comment]
It is from website that has royalty free stock photos, https://www.123rf.com

**Comment by hemanthsavasere** [comment]
I think I need to change it. Royalty free but license is not given

**Comment by hemanthsavasere** [comment]
I think this should be closed as I added a creative commons license file for the background image.

**Comment by niccokunzmann** [comment]
Right. https://github.com/fossasia/flappy-svg/commit/fbc2faa1ba367bb9a4531e529f58333867421eb3
