### ISSUE TITLE
Two background choose-buttons are not working

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#177]
Two buttons that choose the background are not choosing another background.

**Comment by Marauderer97** [comment]
Hello @niccokunzmann ,
I would like to work on this issue
Could this be assigned to me?

**Comment by hemanthsavasere** [comment]
Thanks,

**Comment by Marauderer97** [comment]
@niccokunzmann  I am new to this project and am still trying to figure out the exact working. From what I figured, the function to show the backgrounds(island/binary) are not getting called at all when the image is being clicked. Can you tell me how to proceed?

**Comment by niccokunzmann** [comment]
I do not know. I did not program it. But I guess, looking at the existing backgrounds, you can figure out what is similar and what is different. onclick could be an attribute to look for.

**Comment by niccokunzmann** [comment]
Thanks, I see, you fixed it!
