### ISSUE TITLE
Let user choose background

### ISSUE THREAD

**Issue by rhemon** [fossasia/flappy-svg#180]
It would be nice if all the backgrounds available were listed and shown to the user, from which they can choose. I have seen some are already shown like that, so right now it should be simply adding the rest to that list.

**Comment by Abhi2424shek** [comment]
@rhemon this is shown currently:
![image](https://cloud.githubusercontent.com/assets/8947010/21358167/de98d9a2-c6fd-11e6-91bc-bf5664a4c081.png)

@niccokunzmann what do you say about this.

**Comment by rhemon** [comment]
cool. but i think there were more backgrounds. not sure. but good work.

**Comment by Abhi2424shek** [comment]
@rhemon not my work, someone among the community did it so it's our work right ?

**Comment by Abhi2424shek** [comment]
@niccokunzmann suggestions @rhemon does not have access to close this
