### ISSUE TITLE
No collision takes place in island background 

### ISSUE THREAD

**Issue by hemanthsavasere** [fossasia/flappy-svg#183]
collision not happening in island background, to end the game  and get the score.

**Comment by Marauderer97** [comment]
@hemanthsavasere  I was playing the game and noticed the same issue, but funnily enough I cannot find any file called thunder.svg in the obstacles folder, or in the layers folder. Do you have any ideas on how to fix this?

**Comment by Marauderer97** [comment]
@niccokunzmann So after a lot of debugging effort :P this is what i found, while all other obstacles have multiple shapes(g tags) under the initial layer, thunder only has the layer and no other g tags defined under it. So no obstacles get pushed to the obstacle list and hence there is no obstacle box to check whether or not collision occurs. To fix this, I thing the thunder layer svg bit has to be changed, creating obstacles under the layer
![image](https://cloud.githubusercontent.com/assets/20185076/21229298/2afd0a2a-c307-11e6-975d-2836e21c3dcd.png)The thunder labelled shape
![image](https://cloud.githubusercontent.com/assets/20185076/21229356/5a259024-c307-11e6-95c2-0ea7e505eb9e.png)
Other obstacles like Gotham_obstacles(having  more g  tags under the layer g tag)

**Comment by niccokunzmann** [comment]
okay.

**Comment by hemanthsavasere** [comment]
I am closing it.
