### ISSUE TITLE
No Layer named "ball"

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#187]
![capture](https://cloud.githubusercontent.com/assets/564768/21214521/6e8c3d7c-c29b-11e6-9422-76b1c26687c5.PNG)
When playing the game, sometimes no character is displayed and I get this message.

I would like to see a character there.

There could be a character ball but maybe there is not.

**Comment by Marauderer97** [comment]
@niccokunzmann I would like to work on this. However I cannot find any svg file named ball, a similar thing happened with issue #183 , where I couldnot find any svg file named thunder, What do you suggest?

**Comment by niccokunzmann** [comment]
Currently, we only work on the flappy.svg file.

**Comment by Marauderer97** [comment]
@niccokunzmann 
So how do I look for character ball and fix this?

**Comment by niccokunzmann** [comment]
You can try `grep -r ball`

**Comment by Marauderer97** [comment]
@niccokunzmann 
![image](https://cloud.githubusercontent.com/assets/20185076/21215651/78ea9746-c2c8-11e6-9143-73b7e6464db0.png)
This is what I got, so should I remove Ball from the list, since it doesnot seem to appear elsewhere(and hence probably doesnot exist?)

**Comment by niccokunzmann** [comment]
I do not know...

**Comment by Marauderer97** [comment]
![image](https://cloud.githubusercontent.com/assets/20185076/21215826/8d1e7af6-c2c9-11e6-8b26-7cae9d8ab59e.png)
@niccokunzmann , I am sorry if I am pestering you, it's just that I am still a bit unfamiliar with the project structure, but look, no Ball.svg listed under characters

**Comment by niccokunzmann** [comment]
Hi, I like writing to you, so please do it :)

**Comment by niccokunzmann** [comment]
There are is no ball.svg but ieven if there was, I think, index.html is still only displaying the flappy.svg file. This fale does not use any of the files that are displayed. 
The files were created, so we can move to another project structure later which does not have only one huge svg file which is hard to edit but many small ones.

**Comment by niccokunzmann** [comment]
Did this clarify more? Do you have new questions?

**Comment by Marauderer97** [comment]
@niccokunzmann 
Yes, thank you, this helped :)
I will try looking for the ball component in flappy.svg file then

**Comment by Marauderer97** [comment]
@niccokunzmann , in the flappy svg file, there is no inkscape label with value "ball", This is why the layer is not being rendered. What do you suggest, creating a ball element, or removing ball from the list? 
![image](https://cloud.githubusercontent.com/assets/20185076/21226890/974dee9c-c2fd-11e6-897b-38158a2f9b9d.png)

**Comment by niccokunzmann** [comment]
@Marauderer97 Thanks for the change!
