### ISSUE TITLE
Formatting/Aligning the text on home/welcome screen

### ISSUE THREAD

**Issue by jig08** [fossasia/flappy-svg#19]
In my opinion the text **JoJo Let's Goo** could be aligned such that `Goo` is clearly visible. The overlapping with the sand dunes behind is not giving it a good look.

![screenshot from 2016-01-06 19 52 13](https://cloud.githubusercontent.com/assets/9291400/12144640/1fe5e3b2-b4af-11e5-92bc-64eb3eab45e8.png)

**Comment by harry-7** [comment]
I want to take the task

**Comment by niccokunzmann** [comment]
@harry-7 When you take this task, please also help us, to create new, easy tasks for beginners. I think you are creative and have some ideas about how the game can be changed to the better. Can you write them down as issues? That will help getting students into the game.
@jig08 Can you review it and see if it fits your intention? My suggestion would be to put some white, blurry, transparent background behind it.

**Comment by harry-7** [comment]
@niccokunzmann The game is not yet complete right. So can i add implementing lives and end of game functionality as an issue over there.

**Comment by jig08** [comment]
It looks better than the previous one. I think this issue could be closed and we could create a new task/issue for improvising the Home/Welcome screen. What say @niccokunzmann  ?

**Comment by jig08** [comment]
One theme's welcome screen seems to have been changed, but the other could also be enhanced @harry-7 .

![screenshot from 2016-01-06 23 00 23](https://cloud.githubusercontent.com/assets/9291400/12149348/4b543b9c-b4c9-11e5-98ab-9867a3aac469.png)


![screenshot from 2016-01-06 22 59 59](https://cloud.githubusercontent.com/assets/9291400/12149347/4b53dcf6-b4c9-11e5-9eba-c2c922ec3db2.png)

**Comment by harry-7** [comment]
@jig08  I added one more commit . please have a look at it.

**Comment by jig08** [comment]
Looks better, still there is a scope for improvement especially on the GUI part. Feel free to make necessary changes @harry-7 .

![screenshot from 2016-01-06 23 16 30](https://cloud.githubusercontent.com/assets/9291400/12149765/900c8198-b4cb-11e5-8dff-baf4614b9aa6.png)

**Comment by harry-7** [comment]
@jig08 Can i add an issue to improve the background images that are used ?

**Comment by jig08** [comment]
Sure, go ahead !

**Comment by niccokunzmann** [comment]
Sure, you can create as many issues as you like.

**Comment by harry-7** [comment]
But i cant add labels to it :P

**Comment by jig08** [comment]
@harry-7 We shall add them, Don't worry :)
