### ISSUE TITLE
Change The Play Button's Colour

### ISSUE THREAD

**Issue by reallyly** [fossasia/flappy-svg#190]
I think the play button's colour needs to be changed, because it's hard to see the play button when the background is green like this:
![image](https://cloud.githubusercontent.com/assets/22024041/21284218/aa4bb27c-c447-11e6-858a-edf2fd73d2c3.png)

**Comment by Marauderer97** [comment]
I restyled the play button to look like this, does this look good? @niccokunzmann 
![image](https://cloud.githubusercontent.com/assets/20185076/21285267/b1a4c114-c459-11e6-94e2-d51d8253365e.png)
![image](https://cloud.githubusercontent.com/assets/20185076/21285268/bd4079c8-c459-11e6-93cd-9ffd80fa72c8.png)
Or do you have more ideas?

**Comment by niccokunzmann** [comment]
@Marauderer97 Would you like to create a pull-request, so we can merge the new button?

**Comment by Marauderer97** [comment]
@niccokunzmann Yeah sure, I'll do that, wanted to confirm with you first.

**Comment by niccokunzmann** [comment]
@reallyly if you like, you can have a look an close the issue.

**Comment by reallyly** [comment]
That looks nice @Marauderer97! 

Okay @niccokunzmann :)
