### ISSUE TITLE
No obstacles being displayed in binary background.

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/flappy-svg#192]
There are no obstacles being displayed in binary background, and the game suddenly ends, claiming the user has hit an obstacle. I think this needs to be looked into.
![image](https://cloud.githubusercontent.com/assets/20185076/21285432/4343eaec-c45e-11e6-87ed-faa1bbf2f25d.png)
![image](https://cloud.githubusercontent.com/assets/20185076/21285438/a9754ec8-c45e-11e6-8447-e083951692ef.png)

**Comment by Marauderer97** [comment]
@niccokunzmann I realised this is happening because of the text "101010.." on the layer, can anyone tell me how to go about making such layers in svg so I know how to fix such bugs?

**Comment by niccokunzmann** [comment]
In Inkscape I can use the shortcut Control+Shift+L to open the layers. They are maybe in the view menu.

**Comment by Marauderer97** [comment]
@niccokunzmann I remade the binary background to look like this, now the obstacles display too, hope this works for you..
![image](https://cloud.githubusercontent.com/assets/20185076/21328335/70ff2c60-c659-11e6-9fd0-4cb06452b225.png)

**Comment by Marauderer97** [comment]
@niccokunzmann  This branch is merged, but the binary background in the game is not updated, how come?

**Comment by niccokunzmann** [comment]
I do not know. Are there commits in between? Maybe they reverted the change.
