### ISSUE TITLE
Buttons in Main Menu give Page not found error.

### ISSUE THREAD

**Issue by Marauderer97** [fossasia/flappy-svg#195]
![image](https://cloud.githubusercontent.com/assets/20185076/21286300/1703ee42-c476-11e6-9bee-5a0915c79b95.png)
Clicking on any of the above buttons in the main menu leads to the following error page
![image](https://cloud.githubusercontent.com/assets/20185076/21286303/33dfd184-c476-11e6-9e6c-328d48ec1ffe.png)

**Comment by Marauderer97** [comment]
@niccokunzmann can i add pages for these buttons, so they don't point to invalid pages?

**Comment by niccokunzmann** [comment]
I think, the pages are there. But: the links are not used.

**Comment by Abhi2424shek** [comment]
@Marauderer97 status on this pls?

**Comment by Marauderer97** [comment]
@Abhi2424shek I have fixed 1 of the links.. the otgers I haven't been able to find the pages, comment if you have any suggestions or ideas :)

**Comment by Marauderer97** [comment]
@niccokunzmann I have tried locating the html pages, but they seem to be missing in the flappy svg folder.This is where the links point..
![image](https://cloud.githubusercontent.com/assets/20185076/21483192/5ae2fc0e-cba4-11e6-8d2a-0ff6edf6f113.png)
.... shall I go ahead and add pages for these links then?

**Comment by niccokunzmann** [comment]
Sure, go ahead!

**Comment by Abhi2424shek** [comment]
@Marauderer97 then go ahead we await your awesome PR.
