### ISSUE TITLE
Fix error in "game over" screen

### ISSUE THREAD

**Issue by gaeun** [fossasia/flappy-svg#200]
The game over screen displays score = NaN by default, even when the score is higher than 0. This is a bug that needs to be fixed.

**Comment by niccokunzmann** [comment]
@gaeun You can close it if you think it is solved. Thanks for pointing this out :)

**Comment by gaeun** [comment]
@niccokunzmann Thanks! Could you approve this task (https://codein.withgoogle.com/dashboard/task-instances/6354451176620032/) for the PR I submitted (adding a new character)?

**Comment by niccokunzmann** [comment]
@gaeun I commented.
