### ISSUE TITLE
No collisions happening in Island backround

### ISSUE THREAD

**Issue by hemanthsavasere** [fossasia/flappy-svg#204]
No collisions happening in Island background.

**Comment by hemanthsavasere** [comment]
I don't know if this is labelled as GCI.

**Comment by Marauderer97** [comment]
Changed the thunder background, collisions happen now
![image](https://cloud.githubusercontent.com/assets/20185076/21466110/2d61fbd0-c9e3-11e6-8df5-29dcf1a40ce9.png)
