### ISSUE TITLE
No layer named "black_cat"

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#209]
Currently, the game starts with
![image](https://cloud.githubusercontent.com/assets/564768/21357124/5eacef2c-c6d4-11e6-950d-c659ca7e3181.png)

**Comment by gaeun** [comment]
Oh that's weird. I'm on it right now

**Comment by hemanthsavasere** [comment]
fixed it also

**Comment by hemanthsavasere** [comment]
had to just add layer in svg file

**Comment by hemanthsavasere** [comment]
I think it is fixed.

**Comment by niccokunzmann** [comment]
Cool, yes.

**Comment by Abhi2424shek** [comment]
Yes he's fixed it @niccokunzmann it's working on my part too can you check
