### ISSUE TITLE
Enhance the GUI

### ISSUE THREAD

**Issue by harry-7** [fossasia/flappy-svg#21]
- Improve the Background, Images & Icons used 
  
  _They can be changing the shapes of sun and moon and camel . They can be made some what better. Improvements can also be made to Buildings that are shown in Gotham background etc._
- Work on Home/Welcome Screen
  
  _Welcome screen can be enhanced by improving the images that appear and the header_ **JoJo Let's   Goo** _can be adjusted neatly and appropriate images can be changed to make it look good_
- Enhance the GUI on a whole

You should comment if you like to solve the issue.

**Comment by harry-7** [comment]
@niccokunzmann @jig08  Add some labels to this task. I am unable to add labels.

**Comment by jig08** [comment]
Yes will do, and I have also added a slightly detailed description

**Comment by harry-7** [comment]
@jig08  Its looks better now . Thanks :) . Why am i unable to add labels to the issues ?

**Comment by jig08** [comment]
@harry-7 Would you be working on this ?

**Comment by harry-7** [comment]
No . I intended some one new to do this task :)

**Comment by niccokunzmann** [comment]
@harry-7 Could you characterize the improvements in the description at the top, if you have something in mind? Otherwise you will not see what you had in mind. Maybe even, this can be split into several issues. Formalizing it will show.

**Comment by harry-7** [comment]
@niccokunzmann Have a look at description now. If you have any ideas regarding this issue Feel free to edit the description

**Comment by niccokunzmann** [comment]
I think it is ok. @harry-7 @jig08 I will remove your comments soon, so it does not look crowded from the beginning. They were a meta-discussion which is not useful for people who want to solve the issue.

**Comment by harry-7** [comment]
Those who want to work on the issue . Coment here

**Comment by ashutoshsaboo** [comment]
Hi! I am interested for this. But just before proceeding, would like to clarify a few details. Do you want to improve the GUI of the web version of the game or the android version of it?

**Comment by harry-7** [comment]
This issue is about improving the GUI of web version.

**Comment by niccokunzmann** [comment]
@ashutoshsaboo Welcome, go ahead. @harry-7 created the issue and can also guide you.

**Comment by ashutoshsaboo** [comment]
Thanks @niccokunzmann @harry-7 . I'll look into this, and try and fix this. Could someone guide me, as to which file contains the code responsible for the GUI of the web version? 

Thanks! :)

**Comment by niccokunzmann** [comment]
We use Inkskape to edit the game. Have a look at the [tasks](https://github.com/fossasia/flappy-svg/tree/master/tasks#tasks). They onclude the hints on how to get started and edit the files.

**Comment by harry-7** [comment]
@ashutoshsaboo  If you have grip on svg then you can directly start looking at the shapes drawn in .svg file

**Comment by Abhi2424shek** [comment]
Claiming this as #104 is merged
