### ISSUE TITLE
Blue link to links.html file missing

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#211]
In the bottom right corner, there was a link, a blue one. It is missing.
When you add it, please relace it with an svg version, so it does not get lost so often.

**Comment by Marauderer97** [comment]
I would like to work on this.

**Comment by niccokunzmann** [comment]
@Marauderer97 Sure, please go ahaead.

**Comment by Abhi2424shek** [comment]
Isn't it a blue coloured link icon, it's there plz recheck

**Comment by niccokunzmann** [comment]
Yes, it is there again!

**Comment by Abhi2424shek** [comment]
So can we close this

**Comment by niccokunzmann** [comment]
@Abhi2424shek Would you like to press the merge button from time to time?

**Comment by Abhi2424shek** [comment]
Sure
