### ISSUE TITLE
Improvement ideas for FlappySVG_Android_2

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/flappy-svg#214]
We could improve the app a lot, here are some suggestions:

- Put the app into the google play store [This would increase it's popularity]
- Put the app on Amazon app store

More ideas are accepted.

**Comment by jayvdb** [comment]
Would it be possible to merge FlappySVG_Android_2 into FlappySVG_Android ?

From what I can quickly see, FlappySVG_Android_2 has a more advanced UI, and the main feature that FlappySVG_Android has is offline support.
It would be better if we can have one app that has both sets of features ;-)
And also it would be better if the history of the app code shows features being added each year during (or soon after) GCI.
Then next GCI, participants can use the existing app with lots of features to create even better apps.

**Comment by Abhi2424shek** [comment]
Yep that will be awesome

**Comment by niccokunzmann** [comment]
@jayvdb merging the apps is a nice idea.

**Comment by Abhi2424shek** [comment]
Followup on #266
