### ISSUE TITLE
Cannot reach several Characters

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#221]
There are some characters like Pokeball #220 and black_cat which I can not reach just by clicking the characters.

**Comment by Marauderer97** [comment]
@niccokunzmann do you want to add a button to select a particular character... like we do for backgrounds.. only it will make the screen too cluttered.. otherwise.. if you keep clicking on characters to change them, you can reach black_cat followed by pokeball

**Comment by niccokunzmann** [comment]
Yes, true. I have the game open the whole time and then it is cached. Thanks.
