### ISSUE TITLE
Octodex Character Layer is not working

### ISSUE THREAD

**Issue by Elgayar** [fossasia/flappy-svg#233]
I expect to see my character available to pick. Instead, my character doesn't appear... However, there are no errors...
Any hints on what my problem might be?
Merge: #232

**Comment by Abhi2424shek** [comment]
To make it available to pick you have to place a static IMG code under the Image tags where the characters are place. In the PR you added the character but did not make it available for choosing. See the code which makes other characters appear in flappy.svg file and

**Comment by Marauderer97** [comment]
@Elgayar Has this been fixed? I saw some new commits to the PR?

**Comment by hemanthsavasere** [comment]
Hi @Elgayar,
When I saw the Flappy SVG file the octodex and the botty had same images.
I think that's what is happening.

**Comment by hemanthsavasere** [comment]
fixed it @Elgayar

**Comment by hemanthsavasere** [comment]
![image](https://cloud.githubusercontent.com/assets/11555217/21635001/009e58fe-d281-11e6-8f3b-d1b39ab0
![image](https://cloud.githubusercontent.com/assets/11555217/21635005/06b78f62-d281-11e6-9ca2-a1889d69889f.png)
bca3.png)
![image](https://cloud.githubusercontent.com/assets/11555217/21635010/0c644f5e-d281-11e6-8a62-e1d19d8d3c5e.png)

**Comment by Elgayar** [comment]
Thank you so much :)

**Comment by Elgayar** [comment]
Can you please tell me what exactly was the problem? @hemanthsavasere

**Comment by hemanthsavasere** [comment]
Hey I saw your character in the layers file where each character had their individual svg files, but it was not there in the main flappy.svg file and there was botty character added instead of your octodex.

**Comment by Elgayar** [comment]
Ohh, so it was just a silly mistake :D 
Thanks again!
