### ISSUE TITLE
Android app: Make it playable offline

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#25]
The Flappy Game should be playable without internet connection.

A possible implementation could look like:
- Download the zip file of the project if there is an internet connection. https://github.com/fossasia/flappy-svg/archive/gh-pages.zip
- open/unpack the zip file
- serve the contents via an HTTP-Server to the existing web viewer OR open the local files directly in the web viewer.

I expect it to be about 20-40 lines of code.

Comment if you would like to solve this issue.

**Comment by antoniomdk** [comment]
I would like to solve this issue.

**Comment by jig08** [comment]
@antoniomdk Go Ahead .

**Comment by antoniomdk** [comment]
I did a pull request. I tested in my device and the apps works offline, but I don't know if I used the correct method.

**Comment by niccokunzmann** [comment]
Great work @antoniomdk ! If you like to create pull requests for any changes to the app, you can go ahead, I will review them :) You can claim the [Google Code-In task](https://codein.withgoogle.com/dashboard/tasks/6315213729038336/), if you like. If you would like to do this task again, we can copy it. There is also a task for easy issues. I am really happy to have you contribute.

**Comment by niccokunzmann** [comment]
@antoniomdk Do you have a developer account for the Google-Playstore? If not, I will see what we can do to upload the app.

**Comment by antoniomdk** [comment]
Yes I have a developer account, but I would like to fix some issues before. But if you like, I can upload the app now.

**Comment by niccokunzmann** [comment]
I would view it as a 1.0 version - the basics work. You can upload it as soon as you like. Please tell me, when it is the case. 
What I really like about it: Now, young people can create new characters and after merge, they turn up in an app in the app store :)

**Comment by antoniomdk** [comment]
Ok. I am going to fix #28 and #24 and I will upload the app. I just need some description text of other languages I will write it in Spanish and I will try to write it in English.

**Comment by niccokunzmann** [comment]
I uploaded a structure for the descriptions. They will be valuable for any app to come. If you write the English one, I will add my ideas, translate it to German and maybe to Russian.

**Comment by antoniomdk** [comment]
Ok, Tomorrow, I will write the Spansh one and I will start translating it to English. Translation would be a easy issue. I also think that we should create a branch of android to reduce the game zip.

**Comment by niccokunzmann** [comment]
We have two branches now: 

- gh-pages -  the game
- master all the rest

**Comment by antoniomdk** [comment]
Ok, but How Can I change the branch for commits?

**Comment by niccokunzmann** [comment]
Have a look: http://stackoverflow.com/questions/1783405/checkout-remote-git-branch

**Comment by antoniomdk** [comment]
When I did the pull request,  I set base of máster, and it can be merge correctly. i do not know if it works.

**Comment by niccokunzmann** [comment]
We will see. It looks like it works now: your gh-pages goes into fossasia:master

> antoniomdk wants to merge 1 commit into fossasia:master from antoniomdk:gh-pages
