### ISSUE TITLE
Refactor the credits page with jekyll

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/flappy-svg#257]
The credits page needs to be improved an use jekyll instead of static embedding. @niccokunzmann your views pls

**Comment by niccokunzmann** [comment]
If we use Jekyll, we need an other procedure to download the website for the apps - they download the app from the gh-pages branch and update this way.

Could you go more into detail, what improved means?

**Comment by Abhi2424shek** [comment]
Then we will go for static embedding, the issues page @niccokunzmann looks bad, we could possible materialize it.

**Comment by Abhi2424shek** [comment]
Would open a new issue
