### ISSUE TITLE
Remove a character's onclick function

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#259]
Have a look at https://github.com/fossasia/flappy-svg/pull/258#discussion_r96070640
There, we have all the characters listed.

- [ ] create a function `next_character()` that selects and shows the next character
- [ ] remove the onclick function from  the characters
- [ ] when the website is loaded: set teh onclick attribute to the `next_character` function in all the characters

**Comment by hemanthsavasere** [comment]
Hi @niccokunzmann 
I would like to work on this.

**Comment by Abhi2424shek** [comment]
@hemanthsavasere status on this pls

**Comment by khrisdaniels** [comment]
Is this still open? Where do you want the function to be created? in the Start.js or in Characters SVG?

**Comment by niccokunzmann** [comment]
I think, you can choose what feels best for you.
If it is created once at start, then it should be in the start.js.
However, if you put it in the characters, ....

You can evaluate this.

**Comment by harry-7** [comment]
@niccokunzmann @abishekvashok  I created a pull request solving this issue. Please take a look and let me know if there is anything that needed to be changed
