### ISSUE TITLE
Android App: Open Links in Browser

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#26]
When there are links clicked in the web viewer, they should be opened in the browser.

Assigning middle difficulty because I do not know how to do that.

Comment if you would like to solve this issue.

**Comment by Juanvulcano** [comment]
Hi there! I would like to solve this one :) 
I'm trying to look out for the file that redirects to fossasia.org in the background
May you tell me where is it? Thanks in advance !

**Comment by niccokunzmann** [comment]
Have a look at https://github.com/antoniomdk/flappy-svg/blob/master/FlappySVG_Android/app/src/main/java/fossasia/flappysvg/GameActivity.java
It downloads the game and serves it from the local files.
Also, @antoniomdk wrote the code for the app and can be asked.

I just found a link that could be useful for you. https://developer.android.com/guide/webapps/webview.html#BindingJavaScript
But there may be other ways to directly intercept when the web viewer wants to load a new page. Have fun :)

**Comment by antoniomdk** [comment]
Have a look at Webview client and Javascript code in Android.

**Comment by Abhi2424shek** [comment]
Irrevalent as of #266
