### ISSUE TITLE
Add loading animation

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#260]
The game grows bigger and bigger. Loading can take some time.
Please add a loading information that displays at least at the beginning, when the website is loaded and is not visible when the website is loaded.

**Comment by hemanthsavasere** [comment]
Hi @niccokunzmann,
I can do this.

**Comment by Abhi2424shek** [comment]
Sure!

**Comment by niccokunzmann** [comment]
Sure, please go ahead :)
