### ISSUE TITLE
Why does this game has pathetic graphics

### ISSUE THREAD

**Issue by VRamazing** [fossasia/flappy-svg#269]
Ok this may sound rude and yet the graphics are pathetic and it is really confusing to play as you can't differentiate the background from obstacle.
The way the menu screen and character select screen is displayed is even worse.
As a user I wouldn't play this game.As a developer, I am here to help you out.

**Comment by niccokunzmann** [comment]
You can suggest improvements and create a pull-request.

**Comment by niccokunzmann** [comment]
If you could change the wording so it is more apparent that you value prior efforts, I would very much appreciate it.

**Comment by VRamazing** [comment]
niccokunzmann I would try to improve on this and create a pull request,Thanks for your time.
