### ISSUE TITLE
Android App: Error Output

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#28]
Errors occur and must be caught. Some of them must be shown to the user.

- When the app could not download a new version of the game
- When there is no version of the game because it was never downloaded
- https://github.com/antoniomdk/flappy-svg/commit/a0615baab59734a2f679cdb5731a0a6049d9e9f3#commitcomment-15359600

What are your ideas, @antoniomdk ?

**Comment by antoniomdk** [comment]
* If the app has a previous version of the game, it is playable.
* If there is no previous version of the game: 
  * Send a message: "Please connect to internet to download the game*
* I think that when the apps runs first time, that it shows a progress bar to let users now that it is downloading the game. And in the next times, it does not appear.

**Comment by niccokunzmann** [comment]
@antoniomdk I did not test all the cases listed here. If you are sure that these cases are all in the app, I will close it.

**Comment by antoniomdk** [comment]
Ok, Test it, no problem. I think there are al cases but I prefer you to test it.

**Comment by niccokunzmann** [comment]
Done: 
- "updating app" message

To do:
- "Could not update App" message

Unable to test because I do not know how to delete the files:
- progress bar
- "app is downloaded for the first time" message

**Comment by antoniomdk** [comment]
There is no progress bar, I send an start message and a finish message."app is downloaded for the first time" message: It is "Downloading Game" message.

**Comment by antoniomdk** [comment]
Files are stored in folder named "cachefolder".

**Comment by niccokunzmann** [comment]
I would say this can be closed. Any objections?

**Comment by antoniomdk** [comment]
No objections, you can close it,
