### ISSUE TITLE
Create About Page

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#29]
The start page is really crowded. Create a layer/page named "about".
This layer/page includes:

- The Github link
- The Fossasia Link
- A Link to the Andriod App
- The Link to the rotoscopes, when you click the sun
- A Link back to the game.

Also, remove these links from the start page and add a link to the about page/layer.

Comment if you would like to do this issue.

**Comment by alan-aipe** [comment]
@niccokunzmann  
I would like to do it. But I cant understand how hyperlinks are linked in th start screen. There is no <a> tag anywhere. So how is it linked?

**Comment by niccokunzmann** [comment]
@alan-aipe Yes, you can do it! Go ahead!

**Comment by niccokunzmann** [comment]
#57 closes this.
