### ISSUE TITLE
Andriod App: Only serve local version

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#32]
The Android app uses the online version of the game for download. 
The downloaded version should be used to play the game in order to reduce bandwidth usage and response time.

 Short:
- Always serve the local copy of the game.

**Comment by antoniomdk** [comment]
Can I do this task? I think I can add a "first download progress bar" and after that, run the game. Or maybe I should let other people take issues.

**Comment by niccokunzmann** [comment]
Currently, you are the only one working on this repository. You can solve this issue. It is really simple - thus I did not tag it for google code-in. If you like, go ahead. But please use a different pull-request.

**Comment by antoniomdk** [comment]
In fact,  i have solve It.

**Comment by niccokunzmann** [comment]
Please always reference issues and pull requests with this "#" operator. It allows us to see when people work on issues or to close all issues, once a pull-request is merged.

**Comment by niccokunzmann** [comment]
solved in #33
