### ISSUE TITLE
make obstacles collidable

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#4]
When the bird hits an obstacle, it should collide with it and something should happen. But what? It should be enough for this of there is a method in the bird which is called like

    flappy.collidedWith(obstacle)

This can be something like an `alert`.

Really good would be:
This implementation should run in O(1) and not O(n) where n is the number of obstacles. Do not check every obstacle every move. Only check the closest.

**Comment by niccokunzmann** [comment]
Leave a comment of you want to work on this issue.

**Comment by antoniomdk** [comment]
I think I can do this issue. But, Is there any game loop?

**Comment by niccokunzmann** [comment]
There are several game loops, using the threading.js file. This issue focuses on a good algorithm that works for any kind of obstacles. No behavior is specified. 
I thought of a `Flappy.collidedWith(obstacle)` function. Have a look if that fits. You can do it.

**Comment by antoniomdk** [comment]
Yes, I think I will use flappy:move loop to detect the next obstacle.

**Comment by antoniomdk** [comment]
I have a question. How can I access to SVGElement child?. When I use a layer, I get the obstacle layer SVGElement, but I need to get its children. I tried to use .childNodes but it creates a strange type.

**Comment by niccokunzmann** [comment]
#47 is your pull request 44 but without the android files. You can review the changes.

**Comment by antoniomdk** [comment]
Exactly!

**Comment by niccokunzmann** [comment]
TODO:
 
- When colliding something useful should happen
- check if collision detection runs fast enough

**Comment by niccokunzmann** [comment]
@antoniomdk I added two new issues that should cover what should be done furthermore. If I missed something, tell me. Closing this now, as it is hopefully covered in #71 and #69.

**Comment by antoniomdk** [comment]
It is fine. You could merge game over screen with collision to create an issue.
