### ISSUE TITLE
Game over screen

### ISSUE THREAD

**Issue by antoniomdk** [fossasia/flappy-svg#46]
Create a game over screen. It have to be a layer in the svg file and contains a button to restart the game with functionality.

**Comment by niccokunzmann** [comment]
Also, look at #69.

**Comment by jig08** [comment]
@niccokunzmann We could remove the `GCI` labels now, I believe.

**Comment by SilentFlame** [comment]
@jig08, @niccokunzmann, @antoniomdk   can you guys please guide me as to where I should add the Game over screen.
and where can I see the source code of the main game as need to understand it too.

**Comment by niccokunzmann** [comment]
Have a look at #69. The Game Over screen is in progress. Also, there is a pull-request for it: #85 
This does not mean that we can not have different Game-Over screens. You can create an own Game-Over screen or help to bring the current effort forward.

**Comment by harry-7** [comment]
@niccokunzmann  Is there anything left in this Issue. May be we can close it? I believe its fixed in #89.

**Comment by niccokunzmann** [comment]
@harry-7 looks like it to me, too.
