### ISSUE TITLE
Use hide and show methods for Flappy and Background

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#5]
Flappy and Background have hide and show methods. These should be used preferably before setting the layer's style

**Comment by niccokunzmann** [comment]
Leave a comment of you want to work on this issue.

**Comment by harry-7** [comment]
I want to work on the issue. I need some more explanation on what to do :)

**Comment by niccokunzmann** [comment]
This is a code refactoring task. there are things like style.visibility=none in the code that hide and show elements. these should be replaced with the calls to the objects methods: hide() and show().

Why this is important: In the future this will allow for the hide and show methods to contain e.g. stopping an animation.

**Comment by harry-7** [comment]
ok i am in. i will do the task .

**Comment by niccokunzmann** [comment]
Yes, that is what I mean. I did not remember clearly.

**Comment by harry-7** [comment]
Shall i make layer as a class or just add functions in layer.js file ?

**Comment by niccokunzmann** [comment]
I think, both could be ok. Go for the option which you think you would like to use and which results in understandable and usable code.

**Comment by harry-7** [comment]
Ok . I ll try to make layer as a class and add methods just like gameobject class

**Comment by harry-7** [comment]
I ll make two functions show and hide in layers.js so that any layer can use that method

**Comment by harry-7** [comment]
I created a pull request making necessary changes  as i thought. https://github.com/fossasia/flappy-svg/pull/17

**Comment by niccokunzmann** [comment]
Hi, it looks promising. I added a few comments.

**Comment by harry-7** [comment]
I made one more commit . Please have a look at it

**Comment by niccokunzmann** [comment]
One mistake is still in: Please run the game and test it. The camel does not disappear if you click it at first, because the flappy variable is still null.

**Comment by harry-7** [comment]
I am unable to see the mistake u have mentioned . can u please provide a screen cast or a screen-shots for this.

**Comment by niccokunzmann** [comment]
You are right, I used the wrong commit - now it works perfectly. Thanks. Now, the code looks much better.

You should comment on this at Google Code-In with a link to this issue and submit it so it can be accepted.

**Comment by niccokunzmann** [comment]
Also, create a new pull-request if you would like to be listed under https://github.com/fossasia/flappy-svg/blob/gh-pages/Contributors.md

**Comment by harry-7** [comment]
Thanks :D . Where in the google Code-In can you provide me the link please

**Comment by niccokunzmann** [comment]
So, the link to the task would be https://codein.withgoogle.com/tasks/5378521694208000/
And there is the file https://github.com/fossasia/flappy-svg/blob/gh-pages/Contributors.md
You can add your name and link to it if you like to. You contributed : )

**Comment by niccokunzmann** [comment]
If you have ideas for new issues, they are welcome.

**Comment by harry-7** [comment]
I created a new pr by adding my name to contributors list. I am above 17 years so can i still participate in code-in ? 
This is the pull request https://github.com/fossasia/flappy-svg/pull/18

**Comment by jig08** [comment]
@harry-7 Unfortunately, No.

**Comment by harry-7** [comment]
Its ok . Thanks for merging my pull-request.  :)
