### ISSUE TITLE
Create a task section

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#50]
**Context** 
When Google-Codein is over, we still want to go on writing the game and get new developers into open source. They may even never have programmed before.

**Objective**
Make it as easy for them as it is for Google Code-In students to start.

**Ideas**

- [x] We can copy the English and German task descriptions into a folder
- [x] We should give advice how to start with github, see the Google Code-In task
- [x] People in schools may not have administrator rights - consider that.
- [x] this can be a new repository with a website or a new folder with only md files or pdfs

Please share your thoughts!

**Comment by niccokunzmann** [comment]
We can add the tasks to fossasia's mini-projects & labs repository.

**Comment by jig08** [comment]
@niccokunzmann +1

**Comment by niccokunzmann** [comment]
I copied the tasks from Google Code-In over there: https://github.com/fossasia/flappy-svg/tree/master/tasks#tasks
Feel free to add tasks you think of. They should be "endlessly" repeatable - unlike an issue.

**Comment by niccokunzmann** [comment]
all points are done. closing this.
