### ISSUE TITLE
Create a "Credits" Page

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#58]
There from the links page one should be able to view the contributors of the project.
The are located in the [master branch in the Contributors.md](https://github.com/fossasia/flappy-svg/blob/master/Contributors.md) file. They should be shipped along with the code.

What should be added:
- [x] Names with Links
- [x] License with picture
- [x] a notice where to add the name of contributors in the contributing file

**Comment by SilentFlame** [comment]
@niccokunzmann 
Where exactly you want the link for the "Credits" page to be present.

**Comment by niccokunzmann** [comment]
We moved the links to https://github.com/fossasia/flappy-svg/blob/gh-pages/links.html in order to keep the front page simple. I think, one link there is still free, that can be used. Where would you put it?

**Comment by SilentFlame** [comment]
you mean the link with the paint brush.
yes we can use that for this purpose and can also think to change the logo of that link.
Let's start with first importing just the names and the link part.

**Comment by niccokunzmann** [comment]
Sounds good.

**Comment by SilentFlame** [comment]
So all I need to do is provide the link to Contributors.md file in place of the paint logo.
or do I need to present all this in a good looking html page too.?

**Comment by SilentFlame** [comment]
can we now move to the next phase of this issue.
part 2.
Licence with pictures. 
can you please elaborate the work needed to be done here.

**Comment by niccokunzmann** [comment]
Thanks @SilentFlame for adding the credits page! If you have ideas about how to improve it or the game in general, you should add issues. You can claim them but also others can claim them. An issue is the place to discuss the goal and possible ideas and expected outcomes whereas a pull-request is there to discuss how the code matches the issue. If you separate both, you get better code and a better outcome.

Elaborating on the license: ...

**Comment by niccokunzmann** [comment]
For the License, you can have a look at the LICENSE files and at https://github.com/fossasia/flappy-svg/tree/master#lizenz .

The license ensures that everyone contributing gets credit for that and as long as this is the case, one can use, distribute and modify the game as one likes. 

Have a look at https://creativecommons.org/choose/ . There you can generate the HTML code.

- Title: Flappy SVG
- Attribute work to URL: https://github.com/fossasia/flappy-svg

This page is nice because you can customize your license.

**Comment by SilentFlame** [comment]
Where exactly we need to add this licence?
As I was thinking to add the same licence as that is present in the Flappy-SVG git repo, what do you say?.
and what exactly you mean by Licence with picture, picture of what?

**Comment by niccokunzmann** [comment]
Yes, you can use exactly that. I just wanted to give you more context and the ability to generate the HTML code for it.
You can use the English text and the image in the README.md on the master branch.

**Comment by SilentFlame** [comment]
now where exactly you want this license to be placed?
I mean which file or directory.

**Comment by niccokunzmann** [comment]
I think it should at the bottom of the credits page. This is where I would expect it to be. Which ideas came into your mind?

**Comment by SilentFlame** [comment]
I got bit confused about the things, no problem now things getting in grip. :)

**Comment by SilentFlame** [comment]
now can we proceed to 3rd part and make this issue close.
where exactly do we want to add the notice thing.

**Comment by niccokunzmann** [comment]
In the master branch there is a contributing file which one should read when contributing. It contains hints. There should be a hint that you can add your name and link to the credits page.

**Comment by SilentFlame** [comment]
I have redirected all the `contribution.md`  to `credits.html`.
Now can we please remove this from here as now it does not make any sense.

I'm coming with the PR of part 3.

**Comment by niccokunzmann** [comment]
Looks good. Would it be helpful to add a link to the source of the file somewhere, so one knows immediately where to edit? Would that be useful or not?

**Comment by SilentFlame** [comment]
I guess if someone contributes to this project then he/she must clone and edit it.
In that process it's good for them to add their name down here and would be glad to do so, and this will give the newbies a good experience about the whole procedure.

I guess it's good kept it this way only, as this is a learning thing for the newbies too.

**Comment by SilentFlame** [comment]
but we cab add a link if you like. :)

**Comment by SilentFlame** [comment]
@niccokunzmann 
ain't you on IRC?

**Comment by niccokunzmann** [comment]
Usually I am not on IRC. But it is ok if we discuss it here. Where should I be on IRC? 

Closing this, then.
