### ISSUE TITLE
Add the fossasia logo to the start screen.

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#6]
At the start screen add the fossasia logo and when one clicks it, one should be redirected to the fossasia site.

**Comment by niccokunzmann** [comment]
Leave a comment of you want to work on this issue.

**Comment by shashank-sharma** [comment]
I would like to work on this issue

**Comment by niccokunzmann** [comment]
Sure, you can do that! Please try to find an SVG version of the logo if it exists. It will be smaller in size and have a better resolution.

**Comment by niccokunzmann** [comment]
Great work. Please claim [this task](https://codein.withgoogle.com/tasks/5378521694208000/). We can approve it, then. Please know that this was an easy issue and you should not solve easy issues now. However, adding a character is the next easier task.

**Comment by niccokunzmann** [comment]
Issue closed, #13 and #14 solve it.
