### ISSUE TITLE
Randomize Front Page

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#60]
The front page only shows the camel and the desert.
One can randomize it and show randomly
- [x] different backgrounds
- [x] different characters at the start

Comment if you would like to do solve this issue.

**Comment by mukesh14149** [comment]
Check it out!

**Comment by mukesh14149** [comment]
Check it now @niccokunzmann

**Comment by niccokunzmann** [comment]
Thanks @mukesh14149 ! This issue is solved in my understanding.
