### ISSUE TITLE
Make links and credits page show text when window is resized

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#62]
Looking at 

- http://fossasia.github.io/flappy-svg/links.html
- http://fossasia.github.io/flappy-svg/credits.html

**Problem** When you zoom in, the black background gets bigger and fills the screen so one must zoom out again.
**Wish** when zooming, the writing should still stay where it is but become bigger.
**Possible Solution** one could set the background color to black and remove the div elements that are black.

**Comment by niksj** [comment]
I would like to work on this bug.

**Comment by niccokunzmann** [comment]
Sure, go ahead!

**Comment by SilentFlame** [comment]
Is this solved??
@niksj 
@niccokunzmann 

or can I give It a try.

**Comment by niccokunzmann** [comment]
@niksj did not say anything until now. I forgot to say that asking for help is possible. There is no fork of niksj's. Maybe you can wait a bit for an answer and then decide.

**Comment by SilentFlame** [comment]
@niccokunzmann  
which one of the following should I finalize for the credits.html page?
As the bug is resolved here in both just needs your suggestion on the look part.

I personally like the 1st one.
![one](https://cloud.githubusercontent.com/assets/9693795/13255356/d69e4f72-da6b-11e5-818b-9cae4931d9a8.png)
![two](https://cloud.githubusercontent.com/assets/9693795/13255366/dd73820e-da6b-11e5-90e8-373c356167d1.png)

**Comment by niccokunzmann** [comment]
@SilentFlame we can use the first one. Then I would like to see the bullet points removed. They do not fit in a centered view.

Should "These people have ... :" be a heading? You decide.

**Comment by SilentFlame** [comment]
@niccokunzmann 
Writing the same thing again doesn't make sense. So removing "These people have ......".
Review the final PR.

**Comment by SilentFlame** [comment]
@niccokunzmann 
Above is the final PR related to this issue.
Please have look and if satisfied, then can close the issue.

**Comment by niccokunzmann** [comment]
Thanks @SilentFlame !

**Comment by niksj** [comment]
I'm sorry, I had an accident so could not have a look here.
I'm really sorry for the inconvenience caused due to me @niccokunzmann  & @SilentFlame .

**Comment by niccokunzmann** [comment]
@niksj No problem :)

**Comment by SilentFlame** [comment]
@niksj  nothing to worry :)
