### ISSUE TITLE
Use links instead of onclick="..."

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#63]
Using links instead of onclick= should be able to achieve the same except that now we can choose where to open the link (new tab, same page) and copy it.

Discussion is open!

**Comment by mukesh14149** [comment]
It is better to open links in new tab.

**Comment by mukesh14149** [comment]
@niccokunzmann  this issue should be close, as i already done this in fixed issue #60.

**Comment by niccokunzmann** [comment]
@mukesh14149 You can add you name to the cedits.html file if you like.
