### ISSUE TITLE
Add description of how to get started

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#64]
in the contributing.md:
- [x] link to the tasks

In general:
- [x] add headings to the tasks
- [x] check links in tasks if they still work
- [x] contributing.md moved to credits.html
- [x] add a task about translation
- [x] add links to github/git tutorials

**Comment by sid-10** [comment]
@niccokunzmann I would like to work on this issue. Could you please guide me as to what aspects need to be looked at. Regards.

**Comment by niccokunzmann** [comment]
It should be easy to get started developing this game. If you have ideas on how to make it more beginner friendly, we can discuss them. 
I created a tasks section https://github.com/fossasia/flappy-svg/tree/master/tasks
This issue is about that, currently. 
But I am sure that reaching this section is hard for beginners. If you have ideas on how to guide them e.g. put a link into the credits.html file, ... . You are welcome.
You can ask again. I do not think I explained very well.

**Comment by MahamZafar** [comment]
I would like to work on this issue. Can someone guide me how to get started?

**Comment by niccokunzmann** [comment]
@MahamZafar Hi!

You can find the tasks here: https://github.com/fossasia/flappy-svg/tree/master/tasks
You can edit the pages.
1. Edit & fork - pencil icon
2. Commit changes
3. create pull-request
4. I will look at it and merge it.

You can choose from the tasks above like " add headings to the tasks". But if you find other improvements, they are welcome!
Could I help? May I answer further questions?

**Comment by MahamZafar** [comment]
Hey!
If I want to contribute in "animate a character" task, then I just have to
draw a unique character in Inkscape? Or do I have to manage its movements
through code too?

Regards,
Maham Zafar

**Comment by niccokunzmann** [comment]
You can do that.
You can also take an existing character and add CSS animations.
You can choose. Maybe a start would be an eye of an existing character that always looks at the mouse or rotates.

**Comment by MahamZafar** [comment]
Actually, I have made a character in Inkscape. Kindly have a look.

Regards,
Maham Zafar

**Comment by niccokunzmann** [comment]
Could you create a pull-request?

**Comment by MahamZafar** [comment]
Okay i will do it ow.

Regards,
Maham Zafar

**Comment by MahamZafar** [comment]
Hey!
Thanks a lot for considering my small animated character and adding it in
your open source project. I just needed to confirm that  my character is
not appearing in game play?
I was waiting to play the game with my character.
It will be great if you could add my character.

Regards,
Maham Zafar

**Comment by niccokunzmann** [comment]
@MahamZafar I believe, it is correct, that it does not show up. The game currently only shows the flappy.svg file. The character must be placed in this file. Then, it shows up. #268

**Comment by niccokunzmann** [comment]
@mayonnaise-is-an-instrument Thanks for taking this on!
