### ISSUE TITLE
Do something useful on collision

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#69]
We have code in place that opens a alert window when a Flappy hits an obstacle #4.
The alert should be replaced with something useful.

1. [x] Add Ideas on what should happen.
2. [x] We discuss them.
3. [ ] Someone implements it.

Comment if you would like to work on this issue.

**Comment by mukesh14149** [comment]
We should restart the game again and let the user to select background and characters again. We should also place a score board according to how  far a character has traveled.

**Comment by niccokunzmann** [comment]
- I also think that one can create the score screen at first, showing just a fixed number. We have the issue #45 which cares about the distance counter. 
- Also the score screen does not need to be reachable. We can first create it and use it later.

**Comment by mukesh14149** [comment]
Ok i will work on it!

**Comment by mukesh14149** [comment]
@niccokunzmann i have created a text layer(initially text is a random no.) for score, so is it ok for now or do i need to do something extra for score screen.

**Comment by niccokunzmann** [comment]
I do not see it so I can not say. This is our list:
- [ ] Click something to restart the game
- [ ] character selection (1 and 2 should be solvable be refreshing the site)
- [ ] some shown score (a number)
- [ ] The elements should be visible, readable and recognizable in all cases.
I will check the layer for that.

**Comment by niccokunzmann** [comment]
Thanks @mukesh14149 ! I am closing the issue.
