### ISSUE TITLE
Add a github edge to the startscreen 

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#7]
There are really cool SVG's for github that appear in the corner of the document. Add one of these to redirect to this repository.

- http://codepen.io/elrumordelaluz/pen/XmygWX

**Comment by niccokunzmann** [comment]
Leave a comment of you want to work on this issue.

**Comment by PohSayKeong** [comment]
issue solved at #8

**Comment by niccokunzmann** [comment]
Merged, you can claim the google codein task.

**Comment by niccokunzmann** [comment]
You can 
- add new issues
- create new pull requests without claiming a task 
- for claiming a task you should use the middle and hard issues
