### ISSUE TITLE
Fix links in links.html

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#73]
The links.html file four links in the middle.
If you look how it is implemented, these two if constructs do the switch between the different views the page can be in, in lines [3](https://github.com/fossasia/flappy-svg/blob/gh-pages/javascript/links.js#L3) and [21](https://github.com/fossasia/flappy-svg/blob/gh-pages/javascript/links.js#L21):

	if(document.getElementById('x3').innerHTML.indexOf('i')!=1)
	if(document.getElementById('x4').innerHTML.indexOf('i')!=1)

Better, if we use a variable for the if. We have two views of the page:

1. The initial view when we enter the page
2. The android view after we clicked on the android logo

To solve this issue:

- [x] Add a variable for the view of the page
- [x] use the variable in the if statements
- [x] adjust the `android()` and `contributors()` functions - they could be renamed to "leftImageClick" or something like this.
- [x] Add such a function to the back button so that we can get back from the Android view to the initial view.

Comment if you would like to solve this issue.

**Comment by SilentFlame** [comment]
on it.

**Comment by SilentFlame** [comment]
working on the back button part.

**Comment by SilentFlame** [comment]
do we need to change the name of the functions?
as now it all does make sense.

**Comment by niccokunzmann** [comment]
The names of the functions should describe what they do or what they stand for. You can rename them of cause. I wont judge you for long names as I am extreme on that, having functions with names of 40 characters :)

**Comment by ashutoshsaboo** [comment]
Is this issue still open? Can I work on this?

**Comment by SilentFlame** [comment]
@niccokunzmann but now in the initial phase the name of the functions make sense.
On the later they don't. so what would be your suggestion if we keep the name still the same.

**Comment by niccokunzmann** [comment]
@SilentFlame if it works, it is fine for me. Can you answer @ashutoshsaboo's question on what needs to be done?

**Comment by SilentFlame** [comment]
@ashutoshsaboo,
I have resolved this issue. 
just coming with the final PR soon.
you can review that and the last PR's to have an understanding of the issue.

**Comment by SilentFlame** [comment]
If satisfied with the PR, you can close this issue now. @niccokunzmann

**Comment by niccokunzmann** [comment]
Ok. So after the back-button is merged, we can close it.

**Comment by niccokunzmann** [comment]
Thanks @SilentFlame. Closing it!
