### ISSUE TITLE
Put all images into a folder

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#76]
There are a lot of images now.
All, except the flappy.svg image should be put into one folder, like it is with javascript and style.

- [x] add the images to the folder
- [x] update all links to the images

Comment if you would like to work on this issue.

**Comment by mukesh14149** [comment]
ok i do this

**Comment by SilentFlame** [comment]
It seems that this issue is too resolved under my considering issue.
Hope its all right.
@mukesh14149 can you please have a review of it.

**Comment by mukesh14149** [comment]
yeah sure!

**Comment by niccokunzmann** [comment]
Closing this, done.
