### ISSUE TITLE
Icons and Title

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#77]
- [x] Add a title to the index.html file
- [x] Add the favicon.ico to the credits.html page
- [x] Add a favicon.ico to the links.html page
- [x] The titles should have a similar structure in credits.html, links.html and flappy.html
- [x] The most informing part of the title should be in the first 8 characters

Comment if you would like to work in this issue. We can do several pull-requests for this one.

**Comment by SilentFlame** [comment]
how about the following:

- `Flappy-SVG Game` as the title for index.html

- what exactly for `favicon.ico` needed, and what exactly it does?

- titles consistent across where?

**Comment by shubheksha** [comment]
Hey! I'd like to work on this issue. Should I submit a single PR for all the specified changes? 
Also, is there something specific that needs to be used as the title?

**Comment by oanarosca** [comment]
Hello! I did a little work on this, I hope it helps a bit :)

**Comment by niccokunzmann** [comment]
Hi everyone! Welcome in board! In general: You can submit several pull-requests for one issue and we will discuss them :)

To me it seems like @oanarosca already solved the issue. 
@shubheksha I accidentally merged too fast. If you like, you can still review the merge and tell me whether is issue can be closed and everything is to your satisfaction. 

You are welcome to create issues for your own ideas that you would like in the game. E.g. if you see a bug or if you think that something is not perfect and should be improved. We also have a [tasks](https://github.com/fossasia/flappy-svg/tree/master/tasks#tasks) section where you can choose from other ways to contribute. Issues are for things that can be done only once but the tasks, like adding a character, can be done by several people.

**Comment by niccokunzmann** [comment]
Thanks for contributing! I am closing this issue now.
