### ISSUE TITLE
Link to links.html missing

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#79]
At the front page of http://fossasia.github.io/flappy-svg/ there was a  blue image that linked to the links.html. It disappeared. It should be there again so we can reach the links.html.
Maybe, it was moved into the images folder and the reference was not updated in flappy.svg.

**Comment by mukesh14149** [comment]
Ok i do it

**Comment by niccokunzmann** [comment]
No problem :) We three overlooked something.. Thanks for helping out!

**Comment by SilentFlame** [comment]
is this issue is resolved?
@mukesh14149 
or can I look through it.

**Comment by mukesh14149** [comment]
yes you can.
