### ISSUE TITLE
Add travis.ci tests

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#80]
There is a continuous integration server [travis.ci](https://travis-ci.org) we can use to ensure some facts about the game.
- [ ] Add travis.ci to the [github services](https://github.com/fossasia/flappy-svg/settings/hooks/new?service=travis)
- [ ] add a travis file, in it:
  - [ ] install phantomjs
  - [ ] install node to write the tests
  - [ ] install modules
  - [ ] run tests
- [ ] implement tests
  - [ ] sites are reachable from eachother (index, links, credits, ...)
  - [ ] no resources are loaded from the internet

This issue has to be done step-wise. Comment if you would like to work on it.

**Comment by SilentFlame** [comment]
I would like to learn about this travis.ci thing.
has seen in many oggs github repo.

**Comment by jig08** [comment]
Sure, @SilentFlame go ahead.
Read about [Travis CI](https://travis-ci.org/) and sync this project for easy testing.

**Comment by niccokunzmann** [comment]
Each repository can switch on the travis service. You can go to your forked repository, then settings and services and choose travis-ci and then you can test it on your repository. Tell us when you make progress or you need help :)

**Comment by SilentFlame** [comment]
@niccokunzmann , @jig08  reading through the materials provided now I got a bit idea as how it all works.
will need both of your's guidance as well as help in resolving this issue.
we can proceed to add the travis.ci file to teh repo.


Have some doubts.

- first we need to create tests fir the app.

- listing th dependensies

- installing modules in the repo (I didn't get what that mean).

**Comment by niccokunzmann** [comment]
Can you edit and add the links to the pages where you got these questions? 

Guessing:
- we can create tests later. After the .travis.yml
- I am not sure which dependencies you mean.
- If we use JavaScript to write the tests, we will do it with [nodeJS](https://nodejs.org/en/). Then we need to install packages like a test suite and "phantomjs", a web-browser to run the game in that has no graphical user interface and works well for such tests.

**Comment by Abhi2424shek** [comment]
@SilentFrame still on it.

**Comment by SilentFlame** [comment]
@Abhi2424shek , Sorry but no I'm not working on this currently.

you can carry on.

**Comment by Abhi2424shek** [comment]
I was just asking...

**Comment by SilentFlame** [comment]
No problem at all,
If you like, you can continue. Else just browse through other issues.

**Comment by adarsh-ideal** [comment]
@niccokunzmann I'll work on this.

**Comment by adarsh-ideal** [comment]
I don't have privilege to access webhooks service for fossasia repo.
Please do it Admins.
Checkbox 1

**Comment by adarsh-ideal** [comment]
@niccokunzmann Please review and merge this Pull-Request.
