### ISSUE TITLE
Gotham background: force action by user

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#91]
**Context:**

There is almost no obstacle at the bottom in the Gotham backgound. This means that the player does not need to do anything to play this background. 

**Solution**

Add more obstacles at the bottom of Gothams obstacles.

**Comment by harry-7** [comment]
I would like to work on this.Any ideas on how obstacles should look like :P ?

**Comment by niccokunzmann** [comment]
You are totally free to choose your own.

Additional remarks:

- There are obstacles - the bats. They do not work as obstacles because they are clones.
- It can fit in the setting Batman/Gotham.

Ideas:

- create a batman car
- create one of batmans enemies as rotoscope, see the [get started](https://github.com/fossasia/flappy-svg/blob/master/tasks/add_character/English.md)

**Comment by harry-7** [comment]
>There are obstacles - the bats. They do not work as obstacles because they are clones.

Can I use the existing bats and make them as obstacles? 
>create a batman car

Did you mean creating a batman car as an obstacle?

**Comment by niccokunzmann** [comment]
Yes and yes.

**Comment by harry-7** [comment]
@niccokunzmann  I attatched the svg where I removed all the clones and created obstacles using the given batman. check if it is ok.
[flappy.svg.zip](https://github.com/fossasia/flappy-svg/files/388455/flappy.svg.zip)

**Comment by harry-7** [comment]
@niccokunzmann  Shall I proceed to create a Pull request for this change ?

**Comment by niccokunzmann** [comment]
@harry-7 yes, with a pull-request, I would be able to check this one out, and see the changes you made.  I am able to link and discuss sections. 
You could also send a patch via E-Mail.

**Comment by harry-7** [comment]
@niccokunzmann May be we can close this issue. Do you have any more things on this ?

**Comment by niccokunzmann** [comment]
Let us wait three days. If we close it now, we may not have given a
change to communicate.

Am 30.07.2016 um 20:03 schrieb Hemanth Kumar Veeranki:

**Comment by harry-7** [comment]
@niccokunzmann we can close this now :)
