### ISSUE TITLE
Error: In Gotham Background collision not detected

### ISSUE THREAD

**Issue by jinankjain** [fossasia/flappy-svg#94]
![screenshot from 2016-02-13 19 14 00](https://cloud.githubusercontent.com/assets/3854904/13027935/059885d8-d286-11e5-8917-d364ea27018d.png)

getBox function on Gotham_obstacles is not working

**Comment by mukesh14149** [comment]
#70

**Comment by niccokunzmann** [comment]
I think https://github.com/fossasia/flappy-svg/pull/95/files#diff-f77c6ddae0e61dc2aeb9ac998901e3beR53
fixes this. It was merged some minutes ago. If you like, you can check again.

**Comment by jinankjain** [comment]
I don't think that will fix too. I have tried that too.
ᐧ

**Comment by jinankjain** [comment]
@niccokunzmann yes that error got away but still collision detection don't work

**Comment by niccokunzmann** [comment]
#70 should be the place for discussion why Gotham has no obstacle hits points. Closing this, feel free to comment. It can be reopened.
