### ISSUE TITLE
Make circles in links.html to links

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/flappy-svg#97]
**Context**
The circles in links.html behave as if they should be clickable. When I go over them with the mouse or click them, they change color.

**Problem**
Currently, only the text inside the circles has a behavior although it is suggested that the circles have the same.

**Solution**
Make the circles clickable and do the same that the text inside does now.

**Comment by jinankjain** [comment]
Just above <a> tag above div would solve that problem I guess @niccokunzmann

**Comment by niccokunzmann** [comment]
@jinankjain Some JavaScript functions in links.html will need to be changed, too.

**Comment by SilentFlame** [comment]
@niccokunzmann  please have a look to the PR.
I have added images to both the ```Play Store``` and ```APK``` links. hope it's ok to use here.

**Comment by niccokunzmann** [comment]
@SilentFlame I commented.

**Comment by AMaini503** [comment]
@niccokunzmann  Is this bug still open to work upon ? I would like to work on it.

**Comment by niccokunzmann** [comment]
@AMaini503 You could base your work on #98 The idea is to use images and give proper credit.

**Comment by SilentFlame** [comment]
sorry for my late response, got engaged in my college fest. I'm almost done here just about to submit the final commit, and do some cleaning work.
@AMaini503
but, still you can have a look and suggest some further issues if you notice one. Suggestions always welcomed with regards.

**Comment by SilentFlame** [comment]
@niccokunzmann  I think now this issue should be closed.
